### ISSUE TITLE
rgdal and cairo error

### ISSUE THREAD

**Issue by ykurban** [emanuelhuber/RGPR#19]
ERROR: dependencies ‘rgdal’, ‘Cairo’ are not available for package ‘RGPR’
* removing ‘/usr/local/lib/R/site-library/RGPR’
Installation failed: Command failed (1)

**Comment by emanuelhuber** [comment]
Thank you for this issue that is not directly related to the package RGPR but to your R environment.
Try to install `rgdal` and `Cairo`, either in you R GUI or in the terminal like below:
```r
install.packages(c("rgdal", "Cairo"))
```
Then try again to install `RGPR`. If it is not working, please give me more information/details (on the error message, on the system you are using).
Note: if you are using Mac or Linux, you may need to install the GDAL and Cairo librairies.
