### ISSUE TITLE
code cleanup recommendation

### ISSUE THREAD

**Issue by cellocgw** [emanuelhuber/RGPR#26]
At the top of  fitHyperbola, you do a check on the dimensions of x. (when y= NULL).  May I suggest instead using the function  grDevices::xy.coords instead?  It's a bit cleaner.

**Comment by emanuelhuber** [comment]
Thank you very much for your suggestion. I was not aware of the function grDevices::xy.coords (we can always learn something new). I updated the function hyperbolatFit accordingly.
Don't hesitate to share any suggestions.
