### ISSUE TITLE
Typo: ascci2num should be ascii2num

### ISSUE THREAD

**Issue by Jacob-Lasky** [emanuelhuber/RGPR#37]
https://github.com/emanuelhuber/RGPR/blob/ee8f597d3f8137965837cfd3de71cea1e866a200/R/readIDS.R#L38

I write mostly in python so I'm not 100% sure if I'm reading this correctly, but I believe that there is an error in the function call `ascci2num` which appears on lines 38 and 90 in the `readIDS.R` code.

It is referenced elsewhere as `ascii2num`

**Comment by emanuelhuber** [comment]
Yes, you are correct. Thank you very much!
