### ISSUE TITLE
interger or integer

### ISSUE THREAD

**Issue by NeilParry** [emanuelhuber/RGPR#41]
Possible coding error in readIDS.R

lines 78 through 88 refer to "interger" rather than "integer" which is throwing an error when run.

**Comment by emanuelhuber** [comment]
Thank you for noticing this error. I just corrected this typo. Should now work.
Don't hesitate to contact me if you need any help. Any feedback (especially negative ones) are welcome because they help me to improve RGPR. Best,
Emanuel
