### ISSUE TITLE
Slice Interpolation Issue

### ISSUE THREAD

**Issue by wollaspon** [emanuelhuber/RGPR#54]
I'm having an issue interpolating horizontal GPR slices where no matter what value I use for 'h' I get identical results. I admit that I don't know R and have no idea how mba.surf() uses 'h', but I think this line in the GPRcube class may be the problem:

https://github.com/emanuelhuber/RGPR/blob/867619489fa4eb8e78835a54eb463315cf557391/R/ClassGPRcube.R#L718

**Comment by emanuelhuber** [comment]
Hello @wollaspon 

Thank you for opening this issue and pointing to the solution. I fixed the bug. Let me know it now works and if you need any functionalities.
Best,

Emanuel

**Comment by wollaspon** [comment]
Thanks Emanuel, I can confirm it's working as expected.
