### ISSUE TITLE
Import GPR data link is broken

### ISSUE THREAD

**Issue by TheCre8r** [emanuelhuber/RGPR#57]
On the Readme.md file the `Import GPR data` link is broken

```md
See tutorial [Import GPR data](http://emanuelhuber.github.io/RGPR/00_RGPR_import_data/).
```

Thanks!

TC

**Comment by emanuelhuber** [comment]
Thank you very much, TC, for reporting this broken link!
I fixed it!
Do not hesitate to contact me if you have any question or if you need some specific functionalities.
Best,
Emanuel
