### ISSUE TITLE
Plot contrast settings

### ISSUE THREAD

**Issue by bandtank** [emanuelhuber/RGPR#62]
Is there a way to change the contrast of the data points? It is difficult to see some of the lines in the plot using the RGPR library, but I don't have the same issue with commercial software. I'm not sure if there are other factors at play or what I could be doing differently. Here is an example of the RGPR output:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1170415/230386053-ccb27707-3cab-48f6-959e-ff917de5309f.png">

**Comment by emanuelhuber** [comment]
Thank you very much for raising this issue.
You can clip the signal amplitude. For example:

`plot(x, clip = 0.01)`

That is a linear transformation. Let me know if it solves your problem.
If not, I will find a solution.

Best,

Emanuel

**Comment by bandtank** [comment]
That worked. Thanks.

For anyone else who wants to see the documentation of the clip functionality, go [here](https://github.com/emanuelhuber/RGPR/blob/363beed8cf379535bd84bad08870ff4cdce56f5f/R/plotly.R#L17).

**Comment by emanuelhuber** [comment]
To check the documentation about a function, enter in the r console

```r
?functionName
```

For example

```r
?plot
```

In the documentation the argument `clip` is described.
