### ISSUE TITLE
Horizontal resolution

### ISSUE THREAD

**Issue by terrybok** [emanuelhuber/RGPR#65]
Hello, I'm having difficulty setting the display of files, especially the horizontal resolution. The file opens well but it is stretched over the entire length of the window whereas I would like the scan density, for example 4 scans/cm or 8 scans/cm (indicated in the GSSI's DZX files for an XT for example) to be respected. I don't know if RGPR is capable of displaying a file of several meters (30m)? I would like the display to be 6 meters long and if the file is larger then it will need to be scrolled with the mouse or click on a scroll bar. I have been stuck on this issue for a long time and I have not found any information. Thank in advance..

**Comment by emanuelhuber** [comment]
Hello @terrybok 

Thank you for raising this issue!
I do not think that you can have scrollbars with the classical plots within the R console. Nevertheless, you can try:

- the function `plotly()` from the package `RGPR` (that is based on the `plot_ly()` of the `plotly`-package). You will get an interactive plot, where you can zoom in and out and move the plot. You can maybe control the aspect-ratio of the plot with the arguments `width` and `height`. Check the help on `plotly()`:
    ```
    ?RGPR::plotly
    ```
- export the plot to a PDF or a PNG with the function: `exportPDF()` and `exportPNG()` (set `asp = 1` for an aspect-ratio of 1).
- Another option would be to create a shiny app... but it is a lot of work...

Let me know if it helps you.

Best.

Emanuel

**Comment by terrybok** [comment]
Thank you, I will follow your advice, indeed possible with. Good luck!
