### ISSUE TITLE
Picking of horizon

### ISSUE THREAD

**Issue by arnab-pal** [emanuelhuber/RGPR#82]
Is there any option of horizon picking in RGPR? Automatic or manual, anything will be helpful.

**Comment by emanuelhuber** [comment]
Hello arnab-pal

There is the possibility to do hand picking with the function `delineate()`, have a look at the delineated horizons with `delineations()`, plot the picked horizons with `plotDelineations()` and remove picked horizons with `rmDelineations()`.
The functions are not well documented... I am currently out of town and will send you over next week a short tutorial how to pick profiles.

Best

Emanuel
